- name: tag demo on tasks
  hosts: localhost
  tasks:
    - name: catalogue
      debug:
        msg: Hello from catalogue
      tags: catalogue
    - name: frontend
      debug:
        msg: Hello from frontend
      tags: frontend
    - name: common
      debug:
        msg: common

- name: demo of tag on play level - frontend
  tags: frontend
  hosts: localhost
  tasks:
    - name: frontend
      debug:
        msg: Hello from frontend