- name: conditions
  hosts: localhost
  vars:
    abc: ABC
    val: 100
    apply: true
  tasks:
    - name: condition on string
      ansible.builtin.debug:
        msg: "abc var = ABC"
      when: abc == "ABC"
    - name: condition on string
      ansible.builtin.debug:
        msg: "abc var = abc"
      when: abc == "abc"

    - name: condition on numbers
      ansible.builtin.debug:
        msg: "val var is less than 100"
      when: val | int < 100

    - name: condition on numbers
      ansible.builtin.debug:
        msg: "val var is greater than orr ewual to 100"
      when: val | int >= 100

    - name: run on boolean
      ansible.builtin.debug:
        msg: "Applying"
      when: apply