- name: conditions
  hosts: localhost
  vars:
    abc: ABC
  tasks:
    - name: condition on string
      debug:
        msg: "abc var = ABC"
       when: abc == "ABC"
    - name: condition on string
      debug:
        msg: "abc var = abc"
      when: abc == "abc"