- name: conditions
  hosts: localhost
  vars:
    abc: ABC
    val: 100
  tasks:
    - name: condition on string
      ansible.builtin.debug:
        msg: "abc var = ABC"
      when: abc == "ABC"
    - name: condition on string
      ansible.builtin.debug:
        msg: "abc var = abc"
      when: abc == "abc"

    - name: condition on numbers
      ansible.builtin.debug:
        msg: "val var is less than 100"
      when: val < 100

    - name: condition on numbers
      ansible.builtin.debug:
        msg: "val var is greater than orr ewual to 100"
      when: val >= 100