- name: play1
  hosts: all
  strategy: free
  tasks:
    - name: sleep for 5
      shell: sleep 5
      async: 45
      poll: 0
    - name: sleep for another 5
      shell: sleep 5
      async: 45
      poll: 0

#- name: play2
#  hosts: all
##  strategy: free
#  tasks:
#    - name: sleep for 10
#      shell: sleep 10