- name: Frontend setup
  hosts: FRONTEND
  become: yes
  tags: FRONTEND
  roles:
    - frontend

- name: Mongodb setup
  hosts: MONGODB
  become: yes
  tags: MONGODB
  roles:
    - mongodb

- name: catalogue setup
  hosts: CATALOGUE
  become: yes
  tags: CATALOGUE
  roles:
    - catalogue

- name: redis setup
  hosts: REDIS
  become: yes
  tags: REDIS
  roles:
    - redis