filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - {{LOG_FILE}}
  fields:
    componentName: {{COMPONENT}}
    env: {{ENV}}
    logType: {{LOG_TYPE}}
{% if LOG_TYPE == "json" %}
  json.keys_under_root: true
{% endif %}
  #json.add_error_key: true .. as we do not have any err erro key
  #json.message_key: msg

output.logstash:
  hosts: ["logstash.devops.internal:5044"]

## Defaults
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
