- name: Install Maven
  ansible.builtin.yum:
    name:
      - maven
    state: installed

- name: Aplicaton user setup and download app files
  import_tasks: app-user-setup.yml

#- name: Compile code
#  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
#  args:
#    chdir: /home/roboshop/{{COMPONENT}}
#  become_user: roboshop

- name: Setup service and start service
  import_tasks: systemd.yml

