- name: Install Nodejs
  ansible.builtin.yum:
    name:
      - nodejs
      - npm
      - make
      - gcc-c++
    state: installed

- name: Aplicaton user setup and download app files
  import_tasks: app-user-setup.yml

- name: Install nodejs dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Setup service and start service
  import_tasks: systemd.yml




