- name: Install Maven
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Aplicaton user setup and download app files
  import_tasks: app-user-setup.yml

- name: Install pyhton dependencies
  ansible.builtin.pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

 - name: Show app user info
   debug:
    msg: "{{app_user_info}}"
#
#- name: Setup service and start service
#  import_tasks: systemd.yml

