groups:
{% for component in COMPONENTS %}
  - name: Cart Application Alerts
    rules:
      - alert: Cart Application Down
        expr: "node_systemd_unit_state{job="ec2-nodes-dev", name="cart.service", state="active"}" != 0
        for: 1m
        labels:
          severity: critical
          type: applicationAlert
          kind: serviceAlert
          appName: cart
        annotations:
          summary: {%raw%}"Cart Component Service Down - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}

          description: {%raw%}"Cart Component Service Down - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}
{% endfor %}
#for each and every component we have to write it.(keep code dry,taking help of ansible template)