groups:
{% for component in COMPONENTS %}
  - name: {{component}} Application Alerts
    rules:
      - alert: {{component}} Application Down
        expr: node_systemd_unit_state{job="ec2-nodes-dev", name="{{component|lower}}.service", state="active"} != 1
        for: 1m
        labels:
          severity: critical
          type: applicationAlert
          kind: serviceAlert
          appName: {{component|lower}}
        annotations:
          summary: "{{component}} Component Service Down - IP - {%raw%} [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}

          description: "{{component}} Component Service Down - IP - {%raw%} [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}

{% endfor %}

#for each and every component we have to write it.(keep code dry,taking help of ansible template)